apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This configuration assumes your cluster has cert-manager configured and is using nginx for
# ingress.

bases:
    - ../../base

resources:
    - ingress.yaml


# The following patches update the domain name in the ingress without editing the yaml. 
# Create your own version of the patch file with your domain name and reference in your overlay as
# below:
#patchesJson6902:
#    - path: patch-ingress-host.yaml
#      target:
#          kind: Ingress
#          name: trow-ingress
#          group: extensions
#          version: v1beta1
