apiVersion: v1
kind: Namespace
metadata:
  name: device-plugins
  labels:
    name: device-plugins
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fpga-device-plugin-ds
  namespace: device-plugins
spec:
  selector:
    matchLabels:
      name: fpga-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: fpga-device-plugin-ds
    spec:
      # Mark this pod as a critical add-on; when enabled, the critical add-on
      # scheduler reserves resources for critical add-on pods so that they can
      # be rescheduled after a failure.
      # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
      priorityClassName: "system-node-critical"
      nodeSelector:

      containers:
      - image: uofthprc/fpga-k8s-deviceplugin
        name: fpga-device-plugin-ctr
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
          - name: device-info
            mountPath: /work/device-tree/
            readOnly: true
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: device-info
          hostPath:
            path: /sys/firmware/devicetree/base
