apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trow

# This will start Trow in a StatefulSet along with a persistent volume for data and a service that
# routes to it. 
#
# A working install will require an ingress forwarding a (sub)domain you control to this service.
# This install assumes the ingress terminates TLS; internally Trow is running over http only.
#
# The overlay directories include examples of how to provision ingress on various types of
# Kubernetes cluster.


resources: 
- stateful-set.yaml 
- service.yaml 

#- validate.yaml # Enable for validation webhook
  
images:
- name: containersol/trow
  newTag: "0.2"

# The following patches update the domain name in the trow argument and validator without editing
# the YAML directly.  
# Create your own version of the patch file with your domain name and reference in your
# overlay as below:


patchesJson6902:
#    - path: patch-trow-arg.yaml
#      target:
#        kind: StatefulSet
#        name: trow-set
#        group: apps
#        version: v1
#
#    - path: patch-validator-domain.yaml
#      target:
#        kind: ValidatingWebhookConfiguration
#        name: trow-validator
#        group: admissionregistration.k8s.io
#        version: v1
