apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: trow-data-claim
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: rook-ceph-block
    resources:
        requests:
            storage: 10Gi
